ts-nodeをtsxに置き換へる
Run npx cdk deploy --require-approval never \
/home/runner/work/martian_imperial_year_table/martian_imperial_year_table/cdk/node_modules/ts-node/dist/configuration.js:91
    const { fileExists = ts.sys.fileExists, readFile = ts.sys.readFile, skipProject = index_1.DEFAULTS.skipProject, project = index_1.DEFAULTS.project, tsTrace = index_1.DEFAULTS.tsTrace, } = rawApiOptions;
                                ^

TypeError: Cannot read properties of undefined (reading 'fileExists')
    at readConfig (/home/runner/work/martian_imperial_year_table/martian_imperial_year_table/cdk/node_modules/ts-node/dist/configuration.js:91:33)
    at findAndReadConfig (/home/runner/work/martian_imperial_year_table/martian_imperial_year_table/cdk/node_modules/ts-node/dist/configuration.js:50:84)
    at phase3 (/home/runner/work/martian_imperial_year_table/martian_imperial_year_table/cdk/node_modules/ts-node/dist/bin.js:254:67)
    at bootstrap (/home/runner/work/martian_imperial_year_table/martian_imperial_year_table/cdk/node_modules/ts-node/dist/bin.js:47:30)
    at main (/home/runner/work/martian_imperial_year_table/martian_imperial_year_table/cdk/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/home/runner/work/martian_imperial_year_table/martian_imperial_year_table/cdk/node_modules/ts-node/dist/bin.js:579:5)
    at Module._compile (node:internal/modules/cjs/loader:1871:14)
    at Object..js (node:internal/modules/cjs/loader:2002:10)
    at Module.load (node:internal/modules/cjs/loader:1594:32)
    at Module._load (node:internal/modules/cjs/loader:1396:12)

Node.js v24.18.0
npx ts-node --project tsconfig.json bin/martian-site.ts: Subprocess exited with error 1